### ISSUE TITLE
Is it finished? [question]

### ISSUE THREAD

**Issue by TheLevenCreations** [Project-Aurora/RainbowFox#1]
Hi,

I reach this project by accident, and found it really really cool! RGB mode is just what I need! 👍 You are so great!!!!!!!!!!!!!!

May I ask, is this project finished? Can I use it to print pcb board? 

While it used a different layout, can I just use Whitefox firmware for Rainbowfox? 

Any information would be appreciated. I do not know where to reach you so I just raised an issue here. Please let me know you contact info(email or website) and I will close this issue immediately. 

Thank you very much.

Yours sincerely,
Vincent

**Comment by Project-Aurora** [comment]
The hardware is pretty much good to go,
However Input Club (the same guys that made the WhiteFox and Infinity
Ergodox) are still working on rgb capabillity in their firmware.
They are working on an RGB Tenkeyless design right now.
You can look at their stuff on input.club
Their firmware is designed to be easily adaptable, so once they get it
working I can adapt it to my RGB Projects.

Am 05.11.2016 13:43 schrieb "TheLevenCreations" notifications@github.com:

**Comment by TheLevenCreations** [comment]
Hi, thanks you so much for your quick and nice response. I will keep an eye on input club and also your projects. At the same time, I will close this issue :)

BTW, hope this project will be better and better.

Thanks very much.

Yours sincerely,
Vincent
