### ISSUE TITLE
About the firmware of RainbowFox

### ISSUE THREAD

**Issue by TheLevenCreations** [Project-Aurora/RainbowFox#2]
Hi,

Sorry to bother you again:-)

From the previous issue #1, I awared that the firmware should be different from whitefox because they are using different designs, especially the LED  controller.

After serveral days learning and reading Rainbowfox kicad, MK20 reference doc and IS31FL3737 doc, finally I figure out how it works. Its really a cool design I must say. Before my pcb board printed, I needs to know whether everything works as I expected. So I forked flaggergast's whitefox tmk firmware and updated the code based rainbowfox design.

Since I do not have real pcb board to test, I needs some inputs from some experts like you. Would you like to review my code and let me know, am I moving in the right direction? Any comments are appreciated. THANK YOU VERY VERY MUCH.

Please note, I did not implement auto breath yet, since it should be easy to be turned on once every thing else works fine.

The rainbowfox firmware I developed locates:
https://github.com/TheLevenCreations/RainbowFox_firmware

And there is only one commit for now:
https://github.com/TheLevenCreations/RainbowFox_firmware/commit/4927e6ceb575b7b0fd6221fc9934892ee0141ec5

BTW, I have some questions on pcb design, would you like to take a look, too?

1) In original whitefox design, there is a resistor to GND in PTA5. But in rainbowfox it disappears. For LED safty considerations, would it be better to keep it?
2) In original whitefox, VBAT is linked to 3.3V. But ranbowfox is float. By reading reference, it is used to drive VBAT REGISTER. As far as I can see, in kiihold bootloader implementation, this register is used as loader magic store place during software reset. To keep the same design, would it be better to link it to 3.3V?

Don't know your email box, so I raised an issue again. Sorry for that.

Any things, please let me know. Thanks.

Yours sincerely,
Vincent

**Comment by Project-Aurora** [comment]
I addressed the points you raised in this commit:
https://github.com/Project-Aurora/RainbowFox/commit/d956c5c3914152606eb0eeb9caeb00dc6e36fd84
I can't say all that mouch about the Firmware since I focused on the hardware.
If you decide to build the board I'm definitely willing to help you get the Firmware working.
You can contact me at: owbt01@gmail.com

**Comment by TheLevenCreations** [comment]
Hi @Project-Aurora,

Thanks for your fix. Looks great to me.

At this stage, I definitely WOULD build it. However, my move is quite slow, since this is my first time to build something like this. There are lots of things need to learn.

Anyway, I will let you know how it works.

Btw, there is another finding may you take a look:
3) While the whitefox used a TC1264 to convert 5V to 3.3V, the rainbowfox used internal USB regular as LDO. I can say the benifit is that a component is avoided and it should work well to drive all board devices. Also, this design is the same as teensy 3.1. However, by reading the page in PJRC/teensy 3.2 schematic page (https://www.pjrc.com/teensy/schematic.html), it reads:

Version 3.2 is a minor upgrade to Teensy 3.1. The main change is an improved 3.3V regulator, to allow Teensy to directly power ESP8266 Wifi, WIZ820io (W5200) Ethernet, and other power-hungry 3.3V devices.

From MK20DX256VLH7 data sheet, it reads:
IOHT Output high current total for all ports — 100 mA(max) in page 13

So, it would be a problem if third party want to connect more devices just like Teensy3.1 limitations. As far as I can see, the need to support HUB in merchanical keyboard is really common. For extension consideration, I would say whitefox is doing better. What do you think?

Thanks,
Vincent

**Comment by Project-Aurora** [comment]
If I remember correctly the Whitefox didn't have a dedicated voltage
regulator when I started working on RainbowFox.
I'll go through the commits on their repo tomorrow, to check on it.

**Comment by Project-Aurora** [comment]
Turns out I didn't rememberb correctly.
However a dedicated regulator isn't really needed since 3.3V is only used for signaling, not for actually driving any components (other than the MCU).
USB-HUBs shouldn't need a lot of power at 3.3V either, considering USB is 5V.

**Comment by TheLevenCreations** [comment]
Hi @Project-Aurora 

Just found that TACT switch is changed to PTS810 footprint in the commit last night:
https://github.com/Project-Aurora/RainbowFox/commit/b0b189d81cd4fe479d375338d1ab55b852123eda

However, the RainbowFox.kicad_pcb is not updated to meet this change.

Vincent

**Comment by Project-Aurora** [comment]
You can use the https://github.com/Project-Aurora/RainbowFox/commit/d956c5c3914152606eb0eeb9caeb00dc6e36fd84 Version if you want to use the same switch the Whitefox uses.
Otherwise I properly replaced the Footprint in this commit:
https://github.com/Project-Aurora/RainbowFox/commit/4c8890c1c848ab5f3c78ab5c00050c9d9f135309

**Comment by TheLevenCreations** [comment]
Hi @Project-Aurora,

Thanks for your updates. Looks perfect. I did't buy any switches, resistors yet, so I will use the latest version. Also, the whitefox case design do not need updating - the position of reset switch can match. Well done! :)

For the regular issue, what if 3rd party want to connect 3.3V devices? For example, ESP8266 Wifi, WIZ820io (W5200) Ethernet, and other power-hungry 3.3V devices(quoted in teensy note). Hmmm...I guess in that case, he/she needs another regulator to translate 5V to 3.3V for the own purpose?

Vincent

**Comment by TheLevenCreations** [comment]
One more thing, not a big deal, I think the GND word in RGB footprint is a bit confusing. At the first time I saw it, I thought the LED was common cathode. But after taking a look at schematic, LED should be common anode, as the current flows from CS to SW. Am I right? Probably a COM+ is a better word?

**Comment by Project-Aurora** [comment]
If somebody wants to add wifi/ethernet/bluetooth they need an extra PCB, like an arduino shield.
At that point, adding a voltage regulator isn't too much to ask of them.

I replaced the GND with CA.

**Comment by TheLevenCreations** [comment]
Hi @Project-Aurora,

Looks perfect now. Thanks. I will move on to build it :-)

Vincent
